import {
  SYCM_RANK_LIMITS,
  SYCM_RANK_PREFIX,
  SYCM_RANK_RUNTIME,
  SYCM_RANK_STORAGE_KEYS,
} from '@/shared/constants.js';

const defaultsPayload = {
  DEFAULTS: {
    THROTTLE_MINUTES: SYCM_RANK_LIMITS.DEFAULT_THROTTLE_MINUTES,
  },
  STORAGE_KEYS: SYCM_RANK_STORAGE_KEYS,
  LOG_MAX_ENTRIES: SYCM_RANK_LIMITS.LOG_MAX_ENTRIES,
  LOG_MAX_TABS: SYCM_RANK_LIMITS.LOG_MAX_TABS,
  RANK_MAX_TABS: SYCM_RANK_LIMITS.RANK_MAX_TABS,
  RANK_MAX_ITEMS: SYCM_RANK_LIMITS.RANK_MAX_ITEMS,
  PREFIX: SYCM_RANK_PREFIX,
  RUNTIME: {
    GET_TAB_ID_MESSAGE: SYCM_RANK_RUNTIME.GET_TAB_ID_MESSAGE,
    RANK_CAPTURE: SYCM_RANK_RUNTIME.RANK_CAPTURE,
  },
};

globalThis.__SYCM_RANK_DEFAULTS__ = defaultsPayload;





