import {
  AMCR_LIMITS,
  AMCR_STORAGE_KEYS,
} from '@/shared/constants.js';

globalThis.__AMCR_DEFAULTS__ = {
  STORAGE_KEYS: AMCR_STORAGE_KEYS,
  LOG_MAX_ENTRIES: AMCR_LIMITS.LOG_MAX_ENTRIES,
  LOG_MAX_TABS: AMCR_LIMITS.LOG_MAX_TABS,
  FIND_PAGE_MAX_TABS: AMCR_LIMITS.FIND_PAGE_MAX_TABS,
  FIND_PAGE_SELECTION_MAX_QUERIES: AMCR_LIMITS.FIND_PAGE_SELECTION_MAX_QUERIES,
  FIND_PAGE_SELECTION_MAX_QUERIES_PER_PAGE:
    AMCR_LIMITS.FIND_PAGE_SELECTION_MAX_QUERIES_PER_PAGE,
  FIND_PAGE_SELECTION_MAX_ITEMS_PER_QUERY:
    AMCR_LIMITS.FIND_PAGE_SELECTION_MAX_ITEMS_PER_QUERY,
};





